### ISSUE TITLE
Detected uncommitted changes after build.

### ISSUE THREAD

**Issue by kenhowardpdx** [actions/typescript-action#528] opened 2022-05-18 22:08 UTC
When dependabot bumps the version of dependencies, I routinely get this failure:

```sh
Detected uncommitted changes after build.  See status below:
[18](https://github.com/kenhowardpdx/auto-merge-action/runs/6497746695?check_suite_focus=true#step:6:19)
diff --git a/dist/index.js.map b/dist/index.js.map
[19](https://github.com/kenhowardpdx/auto-merge-action/runs/6497746695?check_suite_focus=true#step:6:20)
index f236678..ef8f2d5 100644
[20](https://github.com/kenhowardpdx/auto-merge-action/runs/6497746695?check_suite_focus=true#step:6:21)
Binary files a/dist/index.js.map and b/dist/index.js.map differ
```

The map file is not necessary for the operation of the action. It would be better if it wasn't included in the package process.

**Comment by SayakMukhopadhyay** [comment] 2022-10-08 17:54
This might be similar to an issue I have been facing. I have noticed that my "Check dist/" workflow never passes and the reason for their failure is that one or more binary files in the `dist` folders differ. 

I have noticed that the `.gitattributes` file in the project marks the content of the `dist` folder to be binary for git. And it seems like git is handling the ignoring of line endings differently in Windows and Linux. Note that this is not an issue with the EOL character as in my case I always use `LF`.

In my case, doing at `git diff` in Windows shows no changes whereas doing a git diff in WSL based Ubuntu shows changes in the files in the `dist` folder. I am not sure if this is an issue with the project or git itself.

Removing the contents of the `.gitattributes` files no longer shows this issue.

**Comment by SayakMukhopadhyay** [comment] 2022-10-09 10:40
So, I did a bit more testing this morning and figured out the root cause. Seems like `npm run package` is generating an `index.js` file with mixed line endings. I have `core.autocrlf=input` set in my `.gitconfig` in Windows but not in WSL and hence the difference in experience.

It seems like the `--ignore-space-at-eol` flag doesn't work with files marked as binary. So, if I do `git diff --ignore-space-at-eol --text dist/`, it shows me there to be no difference and not using the `--text` flag shows my some difference.

**Closed** 2023-08-24 19:01 UTC
